/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e0e3e0",
        "primary": "#18181b",
        "secondary-fixed": "#f4e0c3",
        "on-secondary": "#fff8f1",
        "surface-container": "#edeeeb",
        "inverse-on-surface": "#9d9d9b",
        "error-container": "#fe8983",
        "primary-fixed-dim": "#d6d4d3",
        "secondary-fixed-dim": "#e5d2b6",
        "surface": "#ffffff",
        "inverse-primary": "#ffffff",
        "outline-variant": "#afb3b0",
        "on-tertiary": "#fef8ef",
        "inverse-surface": "#0d0e0e",
        "on-secondary-fixed-variant": "#675a43",
        "tertiary-fixed": "#f9f3ea",
        "surface-container-low": "#f3f4f1",
        "on-background": "#2f3331",
        "on-primary-fixed-variant": "#5c5b5b",
        "error": "#9f403d",
        "surface-variant": "#e0e3e0",
        "surface-container-high": "#e6e9e6",
        "on-tertiary-fixed": "#4c4943",
        "on-secondary-fixed": "#4a3e29",
        "tertiary-dim": "#56534c",
        "on-primary-container": "#525151",
        "outline": "#777c79",
        "surface-dim": "#d6dbd7",
        "on-surface-variant": "#5c605d",
        "secondary": "#6b5d46",
        "surface-bright": "#faf9f7",
        "on-primary-fixed": "#403f3f",
        "on-tertiary-fixed-variant": "#69665f",
        "on-primary": "#faf7f6",
        "surface-container-lowest": "#ffffff",
        "secondary-dim": "#5f513b",
        "on-tertiary-container": "#5f5b54",
        "secondary-container": "#f4e0c3",
        "error-dim": "#4e0309",
        "on-secondary-container": "#5d503a",
        "tertiary-fixed-dim": "#ebe4db",
        "background": "#ffffff",
        "surface-tint": "#5f5e5e",
        "primary-fixed": "#e5e2e1",
        "on-error": "#fff7f6",
        "on-surface": "#18181b",
        "tertiary-container": "#f9f3ea",
        "tertiary": "#625f58",
        "primary-dim": "#535252",
        "on-error-container": "#752121",
        "primary-container": "#e5e2e1"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
